name: Feature Request
description: Suggest a new feature.
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What do you want to happen?
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Proposed implementation
      description: Any thoughts on how this could be implemented (classes, functions, etc.)?
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Anything else worth mentioning.
    validations:
      required: false
